---
# tasks file for reverse-proxy

#
# Remove '{{ reverseproxy_letsencrypt_image }}' container
#
- name: Remove '{{ reverseproxy_letsencrypt_image }}' container
  docker_service:
    project_name:
      "dsc"

    definition:
      version: '2'

      services:
        letsencrypt:
          image: "{{ reverseproxy_letsencrypt_image }}"

    state:
      absent
