---
# tasks file for reverse-proxy

# Stop Nginx service
- name: Stop Nginx service
  systemd:
    unit: reverse-proxy_nginx
    state: stopped
    enabled: false
  # Ignore errors, in case the container does not exist
  # this is for when we restore data prior to bringing up
  # services
  ignore_errors: true
