---
# tasks file for cloud

# Stop Nextcloud service
- name: Stop Nextcloud service
  systemd:
    unit: cloud_nextcloud
    state: stopped
    enabled: false
  # Ignore errors, in case the container does not exist
  # this is for when we restore data prior to bringing up
  # services
  ignore_errors: true
