---
# tasks file for static-site

#
# Create restore folders
#
- name: Create restore folders
  file:
    path: "~/{{ static_site_backup_path }}/apache"
    state: directory
    owner: root
    mode: 0700
#
# Restore data
#
- name: Copy data to remote
  copy:
    src: ./backups/{{ inventory_hostname }}/root/{{ static_site_backup_path }}/apache/apache_data.tgz
    dest: "~/{{ static_site_backup_path }}/apache"
    owner: root
    mode: 0700

- name: Check for uploaded data
  stat:
    path: "~/{{ static_site_backup_path }}/apache/apache_data.tgz"
  register: a1

- name: Failing if needed
  fail:
    msg: "Site data not uploaded!"
  when: a1.stat.exists == false

- name: Check for existing data
  stat:
    path: "/{{ static_site_data_path }}"
  register: a2

- name: Move existing data
  command: "{{ item }}"
  with_items:
    - 'rm -rf /{{ static_site_data_path }}_prev'
    - 'mv /{{ static_site_data_path }} /{{ static_site_data_path }}_prev'
  when: a2.stat.isdir is defined and a2.stat.isdir

- name: Extracting site data
  shell: 'cd /. && tar -xzf ~/{{ static_site_backup_path }}/apache/apache_data.tgz'
