---
# tasks file for common

#
# Install docker-ce package (from Docker)
# TODO: When the Debian project is updated, get this from their package repository
#
- name: Get package apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Get package ca-certificates
  apt:
    name: ca-certificates
    state: present

- name: Get package software-properties-common
  apt:
    name: software-properties-common
    state: present

- name: Set key for Docker package repository
  apt_key:
    state: present
    url: https://download.docker.com/linux/debian/gpg
    
- name: Set Docker package repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian jessie stable"
    state: present
  when: ((ansible_distribution == "Debian") and (ansible_distribution_major_version|version_compare('8', '=')))

- name: Set Docker package repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
    state: present
  when: ((ansible_distribution == "Debian") and (ansible_distribution_major_version|version_compare('9', '=')))

- name: Update the package list, then get Docker-CE
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify:
    - Restart Docker deamon

- name: "Add {{ ansible_user }} to the 'docker' group"
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

## Restart Docker deamon on notification,...now
#- meta: flush_handlers

#
# If not found, install Python package manager (from https://pip.pypa.io)
# TODO: When the Debian project is updated, get this from their package repository
#
- name: Check for Python package manager
  stat:
    path: /usr/local/bin/pip
  register: st

- name: Get pip installer
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: ~/get-pip.py
    mode: ugo+x
  when: st.stat.exists == false

- name: Install Python package manager
  command: python ~/get-pip.py
  when: st.stat.exists == false

#
# Install Python packages docker, docker-compose
#
- name: Install Python package docker
  pip:
    name: docker
    state: present

- name: Install Python package docker-compose
  pip:
    name: docker-compose
    version: 1.9
    state: present
