---
# tasks file for metrics

#
# Remove '{{ metrics_alertmanager_image }}' container
#
- name: Remove '{{ metrics_alertmanager_image }}' container
  docker_service:
    project_name:
      "dsc"

    definition:
      version: '2'

      services:
        alertmanager:
          image: "{{ metrics_alertmanager_image }}"

    state:
      absent

