---
# tasks file for metrics

# Stop Grafana service
- name: Stop Grafana service
  systemd:
    unit: metrics_grafana
    state: stopped
    enabled: false
  # Ignore errors, in case the container does not exist
  # this is for when we restore data prior to bringing up
  # services
#  ignore_errors: true
