---
# tasks file for metrics

#
# Remove '{{ metrics_grafana_image }}' container
#
- name: Remove '{{ metrics_grafana_image }}' container
  docker_service:
    project_name:
      "dsc"

    definition:
      version: '2'

      services:
        grafana:
          image: "{{ metrics_grafana_image }}"

    state:
      absent

