---
# tasks file for metrics

# Stop Node-exporter service
- name: Stop Node-exporter service
  systemd:
    unit: metrics_node-exporter
    state: stopped
    enabled: false
  # Ignore errors, in case the container does not exist
  # this is for when we restore data prior to bringing up
  # services
  ignore_errors: true
