---
# tasks file for metrics

# Stop Prometheus service
- name: Stop Prometheus service
  systemd:
    unit: metrics_prometheus
    state: stopped
    enabled: false
  # Ignore errors, in case the container does not exist
  # this is for when we restore data prior to bringing up
  # services
  ignore_errors: true
